### ISSUE TITLE
dav_ext stat failed

### ISSUE THREAD

**Issue by SOLDIERz** [arut/nginx-dav-ext-module#10]
[alert] 30947#0: *19 dav_ext stat failed on 'file_path', client: IP, server: localhost, request: "PROPFIND /dir/file

is there any fix?

**Comment by bhat3** [comment]
Just for the distinction between this bug and just wrong permission as arut wrote, i got with wrong permissions on Ubuntu 14.04 with "nginx-full" on the server and Nautilus on the client this error while trying to do any file operations:

```
2015/10/07 12:54:11 [alert] 6157#0: *178 dav_ext stat failed on '/var/www/HOST/htdocs/test1' (2: No such file or directory), client: ?.?.?.?, server: HOST, request: "PROPFIND /test1 HTTP/1.1", host: "HOST"
```

On Ubuntu the user and permission for Nginx needs to be "www-data" and at least Nautilus is working now (only tested basic file operations). Kudos to arut for your module :)

**Comment by arut** [comment]
Locking support was added.
