### ISSUE TITLE
Cannot create files on Windows 7

### ISSUE THREAD

**Issue by sbraz** [arut/nginx-dav-ext-module#13]
Hi, it seems there is an issue with the way the module behaves with Windows 7 clients.
When I try to create a file, the client sends a PROPFIND request to which the server replies with an error, and that results in an error on the client side, making it impossible to create new files or folders on the server.
I tried connecting to a WsgiDAV server and although it seems to also reply with a 404 errors, it lets Windows 7 clients create files.
Here is the relevant line when trying to create a text file:

```
2014/02/10 13:41:50 [alert] 20743#0: *2 dav_ext stat failed on '/dav_root/New file.txt', client: xxx, server: xxx, request: "PROPFIND /dav/New%20file.txt HTTP/1.1", host: "xxx"
```

**Comment by feiyx** [comment]
> Hi, it seems there is an issue with the way the module behaves with Windows 7 clients.
> When I try to create a file, the client sends a PROPFIND request to which the server replies with an error, and that results in an error on the client side, making it impossible to create new files or folders on the server.
> I tried connecting to a WsgiDAV server and although it seems to also reply with a 404 errors, it lets Windows 7 clients create files.
> Here is the relevant line when trying to create a text file:
> 
> ```
> 2014/02/10 13:41:50 [alert] 20743#0: *2 dav_ext stat failed on '/dav_root/New file.txt', client: xxx, server: xxx, request: "PROPFIND /dav/New%20file.txt HTTP/1.1", host: "xxx"
> ```

I have this problem too. Have you solved it？

**Comment by arut** [comment]
Escaping has been significantly improved in the last 2 releases. If there's any issue with the new version, please reopen this issue. Until then closing the issue.
