### ISSUE TITLE
No writing support on Windows whatsoever

### ISSUE THREAD

**Issue by zilti** [arut/nginx-dav-ext-module#16]
It's completely impossible to do any writing action from the built-in Windows WebDAV client in Explorer. No upload, no overwrite, nothing. Everything silently fails and locks up Explorer.

**Comment by jonhassall** [comment]
This is because LOCK is not supported.

**Comment by arut** [comment]
Lock support is added.

**Comment by weyou** [comment]
Lock support is not enough for Windows Explorer webclient.   For upload operation, the PROPPATCH method is required.
