### ISSUE TITLE
Support for PROPPATCH

### ISSUE THREAD

**Issue by shauntarves** [arut/nginx-dav-ext-module#18]
Many Java webdav clients make use of the PROPPATCH method. Is it possible for you to add support for that as well?

**Comment by fengyunhe** [comment]
我也发现有这个问题了

**Comment by fengyunhe** [comment]
@shauntarves How do you solve this problem?

**Comment by shauntarves** [comment]
We were not able to solve this problem. We abandoned using this module for webdav.

**Comment by divinity76** [comment]
that doesn't mean this issue should be closed, it's still a real and unsolved issue for the `nginx-dav-ext-module` project
