### ISSUE TITLE
spaces in file or directory names (http://trac.cyberduck.ch/ticket/6094) 

### ISSUE THREAD

**Issue by deadElk** [arut/nginx-dav-ext-module#5]
доброе время суток 

вскрылась ещё одна проблема 
я не уверен это проблема web-dav или web-dav-ext или всё-таки cyberduck-а 
авторы "кибер-утки" переводят стрелы на серверную часть DAV - http://trac.cyberduck.ch/ticket/6094 

спасибо за внимание

**Comment by arut** [comment]
В версии [v2.0.0](https://github.com/arut/nginx-dav-ext-module/tree/v2.0.0) все должно работать.
