### ISSUE TITLE
‘ngx_http_headers_in_t’ has no member named ‘destination’

### ISSUE THREAD

**Issue by fengchen-github** [arut/nginx-dav-ext-module#60]
`nginx-1.18.0]$ ./configure --add-dynamic-module=./nginx-dav-ext-module  $(nginx -V)
`
and make :
```
make -f objs/Makefile
make[1]: Entering directory `/home/centos/nginx-build/nginx-1.18.0'
cc -c -fPIC -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g  -I src/core -I src/event -I src/event/modules -I src/os/unix -I /usr/include/libxml2 -I objs -I src/http -I src/http/modules \
        -o objs/addon/nginx-dav-ext-module/ngx_http_dav_ext_module.o \
        ./nginx-dav-ext-module/ngx_http_dav_ext_module.c
./nginx-dav-ext-module/ngx_http_dav_ext_module.c: In function ‘ngx_http_dav_ext_precontent_handler’:
./nginx-dav-ext-module/ngx_http_dav_ext_module.c:228:29: error: ‘ngx_http_headers_in_t’ has no member named ‘destination’
         dest = r->headers_in.destination;
                             ^
./nginx-dav-ext-module/ngx_http_dav_ext_module.c: In function ‘ngx_http_dav_ext_depth’:
./nginx-dav-ext-module/ngx_http_dav_ext_module.c:1373:26: error: ‘ngx_http_headers_in_t’ has no member named ‘depth’
     depth = r->headers_in.depth;
                          ^
make[1]: *** [objs/addon/nginx-dav-ext-module/ngx_http_dav_ext_module.o] Error 1
make[1]: Leaving directory `/home/centos/nginx-build/nginx-1.18.0'
make: *** [build] Error 2
```

**Comment by thematrixdev** [comment]
May I know how did you solve the issue please?

**Comment by fengchen-github** [comment]
> May I know how did you solve the issue please?

Change $(nginx -V) to the real value

**Comment by thematrixdev** [comment]
what is the "real value"? $(nginx -V) gives all the options when the original nginx was compiled.
By the way may I know the nginx version you used to compile?

**Comment by fengchen-github** [comment]
> what is the "real value"? $(nginx -V) gives all the options when the original nginx was compiled. By the way may I know the nginx version you used to compile?

nginx-1.18.0
`
 ./configure --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib64/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --user=nginx --group=nginx --with-compat --with-file-aio --with-threads --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_flv_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-mail --with-mail_ssl_module --with-stream --with-stream_realip_module --with-stream_ssl_module --with-stream_ssl_preread_module --with-cc-opt='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -fPIC' --with-ld-opt='-Wl,-z,relro -Wl,-z,now -pie' --add-dynamic-module=./nginx-dav-ext-module
`
then
`
make
`

**Comment by lzy-safe** [comment]
lua-nginx-module-0.10.21/src/ngx_http_lua_headers_in.c:156 error: 'NGX_ http_ headers_ in_ T 'has no member named' cookies'
why?May I know how did you solve the issue please?
