### ISSUE TITLE
please add lock feature

### ISSUE THREAD

**Issue by ifooth** [arut/nginx-dav-ext-module#8]
please add lock feature! 
webdav class 2

**Comment by anatoli26** [comment]
Hi @arut, I'm also willing to contribute economically to the full webdav support with locks. Could you please let us know how much is required so we collect needed funds on bountysource.com or similar platform? The problem is that without locks there's no write access on OS X, so the whole thing is quite unusable.

**Comment by grigory51** [comment]
+1

**Comment by anatoli26** [comment]
Hi @arut, I see some changes in the repo. Could you please consider adding this feature? This is IMO the most important feature lacking as its absence makes impossible using this extension with a number of webdav client implementations, in particular MacOS.

**Comment by jonhassall** [comment]
+1

**Comment by alehaa** [comment]
Does someone know, if there's a easy to read documentation on the lock feature, so maybe we could write a patch for this feature?

**Comment by anatoli26** [comment]
AFAIK, this is not a simple feature if you don't know well the NginX internals, as it requires to maintain a DB of locks. I suggest you to check the implementation details of Cyrus IMAP (the HTTP module and xDAV features): https://github.com/cyrusimap/cyrus-imapd/blob/master/imap/http_dav.c.

By the way, if you deploy MDA (Mail Delivery Agent) in your organization (like Dovecot, etc.) I'd recommend you to migrate to Cyrus and have 2-in-1: MDA + xDAV (CalDAV, CardDAV and WebDAV). It works well with all devices and is super easy to configure. This is what we've finally implemented and we're completely satisfied with the result.

**Comment by JoeKun** [comment]
@alehaa Would you mind telling us which python WebDAV server you used?

**Comment by arut** [comment]
Guys, I've just pushed a branch [v2locks](https://github.com/arut/nginx-dav-ext-module/tree/v2locks) with locking support. It currently works at least with the MacOS client. Any feedback is highly appreciated.

**Comment by arut** [comment]
Locking added.
