### ISSUE TITLE
The problem with UrlEncode/UrlDecode！

### ISSUE THREAD

**Issue by codywon** [arut/nginx-dav-ext-module#9]
Hi，Arut ！
I use the module to build the webdav server.when I upload a file with Chinese character name,the filename is  你好 ,But it dispaly like "%E4%BD%A0%E5%A5%BD" ,I can't solve the case! please help,thank you!

**Comment by chrysn** [comment]
the 0.0.3 version currently used in debian still shows the issue codywon described. #17 looks like a good patch for it.

**Comment by arut** [comment]
This seems to be fine in the [v2](https://github.com/arut/nginx-dav-ext-module/tree/v2) branch, which will eventually become a new release.

**Comment by arut** [comment]
[v2.0.0](https://github.com/arut/nginx-dav-ext-module/tree/v2.0.0)
